### ISSUE TITLE
Initial Release Roadmap

### ISSUE THREAD

**Issue by ayuka** [lunarlang/lunar#38]
**TODO:** Not a lot of things have been properly tracked before this, so it is difficult to catch everything that has been completed thus far. Additionally, credits have not been properly given as I'm unsure who is responsible for what. If you are responsible for something that is not credited, please let me know immediately. Also, if something is improperly checked (or not), please let me know about that too.

- [x] Class support @Apakovtac 
  - [x] Allow classes to extend from other classes
- [x] Importing and Exporting between scripts @headjoe3 
- [x] Self-assignment operators @Apakovtac 
- [ ] Type system
  - [x] Preliminary work implemented @headjoe3 
- [ ] Create issue and pull request templates #37 @ChasingSpace 
  - [ ] ~~Upon an unexpected error, link user to the `New Issue` page with the error message written out already.~~
- [x] Standalone executable binaries for Windows and Linux @ChasingSpace 
  - [ ] Update CI build to fetch the latest release instead of using `lib` which includes an older version of Lunar for compiling.
- [ ] Rewrite the Lunar compiler *(lunarc)* #39 @ChasingSpace @Apakovtac
